name: Test and Build Email API Service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_ENV: production
  PORT: 3000

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci --include=dev
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Build Docker image
      run: docker build -t email-api-service .
    
    - name: Success message
      run: |
        echo "✅ Tests pasaron exitosamente!"
        echo "✅ Build completado!"
        echo "✅ Docker image construida!"
        echo ""
        echo "🚀 Para desplegar manualmente:"
        echo "1. Clona el repositorio en tu servidor"
        echo "2. Configura las variables de entorno"
        echo "3. Ejecuta: npm run deploy:prod"
        echo "   o: docker run -p 3000:3000 email-api-service" 